# path to the 4D STEM data
path_4dstem_data: /path/to/4d_data

# imaging condition
voltage: 300  # in kV
aperture: 20  # in mrad

# sampling condition
sampling_real_space: [0.1, 0.1]  # in angstroms
sampling_reciprocal_space: [0.01, 0.01]  # in inverse angstroms

# detector parameters
rotation_offset_diff_plane_deg: 0.0  # in degrees